import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { PageHeader, Descriptions, Table, Button, Tag, message, Modal, Form, Input } from 'antd'
import {InfoOutlined,PlusOutlined} from '@ant-design/icons'
import { useState } from 'react'

import { Layout, Menu } from 'antd'
import Container from '../../components/container'

const { Content } = Layout

function renderPageAction() {
  return (
    <Button
      type="primary"
      icon={<PlusOutlined />}
    >
      Add Roadmap
    </Button>
  )
}

function renderTableAction() {
  return (
  <Button
    shape="circle"
    type="primary"
    ghost
    icon={<InfoOutlined />}
    // onClick={() => { this.handleGoToCustomerDetail(id) }} 
    />
  )
}

export default function Roadmap() {
  const [selected, setSelected] = useState('');

  const columns = [
    {
      title: 'ID',
      key: 'id',
      dataIndex: 'id',
      width: 30,
    },
    {
      title: 'Title',
      key: 'title',
      dataIndex: 'title',
      width: 500,
    },
    {
      title: "Action",
      key: 'Action',
      dataIndex: 'action',
      render: renderTableAction,
      width: 10,
    },
  ]
  const data = [{
    id: "1bb4cbff",
    title: "roadmap 1"
  }]
  return (
    <div className={styles.container}>
      <Head>
        <title>Roadmap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Content
            className="site-layout-background"
            style={{
              padding: 24,
              margin: 0,
              minHeight: 280,
            }}
          >
            <Layout>
              <PageHeader
                title="Roadmap"
                extra={renderPageAction()}
                >
                <Descriptions size="small" column={4}>
                  <Descriptions.Item label="Total" key="total">{data.length} Roadmap</Descriptions.Item>
                </Descriptions>
              </PageHeader>
              <div className={styles.table}>
                <Table
                  columns={columns}
                  dataSource={data}
                  pagination={false}
                  scroll={{ x: true, y: 'calc(100vh - 260px)' }} />
              </div>
            </Layout>
          </Content>
        </Container>
      </main>
    </div>
  )
}
