import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { PageHeader, Descriptions, Table, Button, Tag, message, Modal, Form, Input } from 'antd'
import {InfoOutlined,PlusOutlined} from '@ant-design/icons'
import { useState } from 'react'
import { Layout, Menu } from 'antd'
import Container from '../../components/container'

const { Content } = Layout

function renderPageAction() {
  return (
    <Button
      type="primary"
      icon={<PlusOutlined />}
    >
      Add Class
    </Button>
  )
}

function renderTableAction() {
  return (
    <Button
      shape="circle"
      type="primary"
      ghost
      icon={<InfoOutlined />}
    />
  )
}

export default function Class() {
  const [selected, setSelected] = useState('');

  const columns = [
    {
      title: 'ID',
      key: 'id',
      dataIndex: 'id',
      width: 30,
    },
    {
      title: 'Title',
      key: 'title',
      dataIndex: 'title',
      width: 400,
    },
    {
      title: 'Action',
      key: 'action',
      dataIndex: 'action',
      render: renderTableAction,
      width: 30,
    },
  ]
  const data = [{
    id: "7a95db96",
    title: "Live class 1",
  }]
  return (
    <div className={styles.container}>
      <Head>
        <title>Class</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Content
            className="site-layout-background"
            style={{
              padding: 24,
              margin: 0,
              minHeight: 280,
            }}
          >
            <Layout>
              <PageHeader
                title="Class"
                extra={renderPageAction()}
              >
                <Descriptions size="small" column={4}>
                  <Descriptions.Item label="Total" key="total">{data.length} Class</Descriptions.Item>
                </Descriptions>
              </PageHeader>
              <div className={styles.table}>
                <Table
                  columns={columns}
                  dataSource={data}
                  pagination={false}
                  scroll={{ x: true, y: 'calc(100vh - 260px)' }} />
              </div>
            </Layout>
          </Content>
        </Container>
      </main>
    </div>
  )
}
