import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { PageHeader, Descriptions, Table, Button, Tag, message, Modal, Form, Input } from 'antd'
import { PlusOutlined, SettingOutlined, DeleteOutlined } from '@ant-design/icons'
import { useState } from 'react'

import { Layout, Menu } from 'antd'
import Container from '../../components/container'

const { Content } = Layout

function renderPageAction() {
  return (
    <Button
      type="primary"
      icon={<PlusOutlined />}
    // onClick={this.handleToggleAddUserModal}
    >
      Add User
    </Button>
  )
}

function renderTableAction() {
  return (
    <>
      <Button
        shape="circle"
        icon={<SettingOutlined />}
      // onClick={() => { this.handleToggleEditUserModal(User) }} 
      />
      <Button
        type="danger"
        shape="circle"
        icon={<DeleteOutlined />}
        ghost
        // onClick={() => { this.handleDeleteUser(User) }}
        className={styles.tableActionButton} />
    </>
  )
}
export default function User() {
  const [selected, setSelected] = useState('');

  const columns = [
    {
      title: 'Email',
      key: 'email',
      dataIndex: 'email',
      width: 140,
    },
    {
      title: 'Name',
      key: 'name',
      dataIndex: 'name',
      width: 300,
    },
    {
      title: "Action",
      key: 'action',
      dataIndex: 'action',
      render: renderTableAction,
      width: 30,
    },
  ]
  const data = [{
    email: "admin@portoapp.id",
    name: "admin"
  }]
  return (
    <div className={styles.container}>
      <Head>
        <title>User</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Content
            className="site-layout-background"
            style={{
              padding: 24,
              margin: 0,
              minHeight: 280,
            }}
          >
            <Layout>
              <PageHeader
                title="User"
                extra={renderPageAction()}
                >
                <Descriptions size="small" column={4}>
                  <Descriptions.Item label="Total" key="total">{data.length} User</Descriptions.Item>
                </Descriptions>
              </PageHeader>
              <div className={styles.table}>
                <Table
                  columns={columns}
                  dataSource={data}
                  pagination={false}
                  scroll={{ x: true, y: 'calc(100vh - 260px)' }} />
              </div>
            </Layout>
          </Content>
        </Container>
      </main>
    </div>
  )
}
