import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { PageHeader, Descriptions, Table, Button, Tag, message, Modal, Form, Input } from 'antd'

import { useState } from 'react'

import { Layout, Menu } from 'antd'
import Container from '../../components/container'

const { Content } = Layout

export function NewsModal() {
  const [showing, setShowing] = useState(false)
  return (
    <Modal
      title="Add New News"
      visible={showing}
      okText="Submit"
      // confirmLoading={submitting}
      width={520}
      forceRender
      // onOk={(this.form.current || {}).submit}
      // onCancel={onClose}
      >
      <Form
        // ref={this.form}
        layout="vertical"
        // onFinish={onSubmit}
        >
        <Form.Item
          label="Location Name"
          name="name"
          required
          rules={[
            {
              required: true,
              message: 'name is required',
            },
          ]}>
          {/* <Input disabled={submitting} /> */}
        </Form.Item>
        <Form.Item
          label="Location Address"
          name="address"
          required
          rules={[
            {
              required: true,
              message: 'Address is required',
            },
          ]}>
          <Input.TextArea
            autoFocus
            // disabled={submitting} 
            />
        </Form.Item>
      </Form>
    </Modal>
  )
}

export default function News() {
  const [selected, setSelected] = useState('');

  const columns = [
    {
      title: 'Location Id',
      key: 'id',
      dataIndex: 'id',
      width: 140,
    },
    {
      title: 'Location Name',
      key: 'name',
      dataIndex: 'name',
      width: 180,
    },
    {
      title: 'Location Address',
      key: 'address',
      dataIndex: 'address',
      width: 160,
    },
  ]
  const data = []
  return (
    <div className={styles.container}>
      <Head>
        <title>News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Content
            className="site-layout-background"
            style={{
              padding: 24,
              margin: 0,
              minHeight: 280,
            }}
          >
            <Layout>
              <PageHeader
                title="News"
              >
                <Descriptions size="small" column={4}>
                  <Descriptions.Item label="Total" key="total"> News</Descriptions.Item>
                </Descriptions>
              </PageHeader>
              <div className={styles.table}>
                <Table
                  columns={columns}
                  dataSource={data}
                  pagination={false}
                  scroll={{ x: true, y: 'calc(100vh - 260px)' }} />
              </div>
              <NewsModal
                title="Create new Recycle Location"
                />
            </Layout>
          </Content>
        </Container>
      </main>
    </div>
  )
}
