import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import { PageHeader, Descriptions, Table, Button, Tag, message, Modal, Form, Input } from 'antd'
import {InfoOutlined} from '@ant-design/icons'
import { useState } from 'react'

import { Layout, Menu } from 'antd'
import Container from '../../components/container'

const { Content } = Layout

function renderTableAction() {
  return (
  <Button
    shape="circle"
    type="primary"
    ghost
    icon={<InfoOutlined />}
    // onClick={() => { this.handleGoToCustomerDetail(id) }} 
    />
  )
}


export default function Customer() {
  const [selected, setSelected] = useState('');

  const columns = [
    {
      title: 'Email',
      key: 'email',
      dataIndex: 'email',
      width: 140,
    },
    {
      title: 'Name',
      key: 'name',
      dataIndex: 'name',
      width: 180,
    },
    {
      title: 'Phone Number',
      key: 'phoneNumber',
      dataIndex: 'phoneNumber',
      width: 160,
    },
    {
      title: "Action",
      key: 'action',
      dataIndex: 'action',
      render: renderTableAction,
      width: 50,
    },
  ]
  const data = [{
    id:1,
    name: "Pablo",
    email: "pablo@mail.com",
    phoneNumber: "0812345678"
  }]
  return (
    <div className={styles.container}>
      <Head>
        <title>Customer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Content
            className="site-layout-background"
            style={{
              padding: 24,
              margin: 0,
              minHeight: 280,
            }}
          >
            <Layout>
              <PageHeader
                title="Customer"
              >
                <Descriptions size="small" column={4}>
                  <Descriptions.Item label="Total" key="total">{data.length} Customer</Descriptions.Item>
                </Descriptions>
              </PageHeader>
              <div className={styles.table}>
                <Table
                  columns={columns}
                  dataSource={data}
                  pagination={false}
                  scroll={{ x: true, y: 'calc(100vh - 260px)' }} />
              </div>
            </Layout>
          </Content>
        </Container>
      </main>
    </div>
  )
}
