import Head from 'next/head'
import { connect } from 'react-redux'
import styles from '../../styles/Home.module.css'
import { PageHeader, Descriptions, Table, Button, Tag, message, Modal, Form, Input } from 'antd'
import { PlusOutlined, SettingOutlined, DeleteOutlined } from '@ant-design/icons'
import { getRoles } from '../../store/Actions/RoleAction';
import { Layout, Menu } from 'antd'
import Container from '../../components/container'
import { useEffect } from 'react';

const { Content } = Layout
const mapStateToProps = state => {
  return { roles: state.RoleReducer.roles }
}
const mapDispatchToProps = {
  getRoles
}

function renderPageAction() {
  return (
    <Button
      type="primary"
      icon={<PlusOutlined />}
    // onClick={this.handleToggleAddRoleModal}
    >
      Add role
    </Button>
  )
}

function renderTableAction() {
  return (
    <>
      <Button
        shape="circle"
        icon={<SettingOutlined />}
      // onClick={() => { this.handleToggleEditRoleModal(role) }} 
      />
      <Button
        type="danger"
        shape="circle"
        icon={<DeleteOutlined />}
        ghost
        // onClick={() => { this.handleDeleteRole(role) }}
        className={styles.tableActionButton} />
    </>
  )
}
function Roles(props) {
  const { roles, getRoles } = props
  useEffect(() => {
    getRoles()
  }, [])
  const columns = [
    {
      title: 'Role',
      key: 'role',
    },
    {
      title: "Action",
      key: 'action',
      dataIndex: 'action',
      render: renderTableAction,
      width: 107,
    },
  ]

  const data = ["Admin"]
  return (
    <div className={styles.container}>
      <Head>
        <title>Roles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Content
            className="site-layout-background"
            style={{
              padding: 24,
              margin: 0,
              minHeight: 280,
            }}
          >
            <Layout>
              <PageHeader title="Roles" extra={renderPageAction()}/>
              <div className={styles.table}>
                <Table
                  columns={columns}
                  dataSource={data}
                  pagination={false}
                  scroll={{ x: true, y: 'calc(100vh - 260px)' }} />
              </div>
            </Layout>
          </Content>
        </Container>
      </main>
    </div>
  )
}

export default connect(mapStateToProps, mapDispatchToProps)(Roles)